### ISSUE TITLE
I'm interested

### ISSUE THREAD

**Issue by vech2514** [BYUCS452F2021/Rummage#2]
Hey I'm Ben White. I like this idea because for one it actually seems to be heavily dependent on databases which quite a few other options don't seem to even need one, and two I think it's actually a neat idea. I've held several school and professional positions as a web application developer. I have a lot of experience with HTML, CSS, JavaScript, Java, C#, SQL, and NoSQL Databases. I'm the resident expert at SQL and NoSQL databases at my current job at the Center for Family History and Genealogy here at BYU which is 60% SQL databases (but transitioning to NoSQL). Additionally, I'm a very self-motivated person when it comes to projects so not only will I get my shares done but I'll be a great help in driving discussion and problem solving as a team.

**Comment by nathanposton** [comment]
Hi Ben,

I love your experience, tackling a database with a resident database expert sounds like a recipe for success to me. I just added you to the repo as an admin. Looking forward to working with you!
