### ISSUE TITLE
I'm interested

### ISSUE THREAD

**Issue by cjbeacon** [BYUCS452F2021/Rummage#3]
Hi, I'm Caleb Johnson. I think this is a great serious idea that has viable potential to see real use. I've worked on the 240 project myself a while back, and am pretty familiar with Android Programming in particular. I've worked a bit with connecting Android Apps to AWS hosted databases before using Lambda and SQS in the past during 340. Over my summer internship I worked with UX designers on my team a lot and learned to be better at identifying how to make apps user friendly.

**Comment by nathanposton** [comment]
Hi Caleb,

That's exactly the experience we need, we'd be glad to have you. I just gave you repo rights. Looking forward to working with you!
